"""empty message

Revision ID: 002f9385d89d
Revises: effd5f580da2
Create Date: 2020-07-10 07:59:05.271169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '002f9385d89d'
down_revision = 'effd5f580da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('name_en', sa.String(length=30), nullable=True))
    op.add_column('company', sa.Column('name_ja', sa.String(length=30), nullable=True))
    op.add_column('company', sa.Column('name_ko', sa.String(length=30), nullable=True))
    op.add_column('company', sa.Column('tag_en', sa.Text(), nullable=True))
    op.add_column('company', sa.Column('tag_ja', sa.Text(), nullable=True))
    op.add_column('company', sa.Column('tag_ko', sa.Text(), nullable=True))
    op.drop_column('company', 'company_name_ko')
    op.drop_column('company', 'company_tag_en')
    op.drop_column('company', 'company_tag_ja')
    op.drop_column('company', 'company_tag_ko')
    op.drop_column('company', 'company_name_ja')
    op.drop_column('company', 'company_name_en')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('company_name_en', mysql.VARCHAR(collation='utf8_unicode_ci', length=30), nullable=True))
    op.add_column('company', sa.Column('company_name_ja', mysql.VARCHAR(collation='utf8_unicode_ci', length=30), nullable=True))
    op.add_column('company', sa.Column('company_tag_ko', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True))
    op.add_column('company', sa.Column('company_tag_ja', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True))
    op.add_column('company', sa.Column('company_tag_en', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True))
    op.add_column('company', sa.Column('company_name_ko', mysql.VARCHAR(collation='utf8_unicode_ci', length=30), nullable=True))
    op.drop_column('company', 'tag_ko')
    op.drop_column('company', 'tag_ja')
    op.drop_column('company', 'tag_en')
    op.drop_column('company', 'name_ko')
    op.drop_column('company', 'name_ja')
    op.drop_column('company', 'name_en')
    # ### end Alembic commands ###
