"""empty message

Revision ID: 46719ce46e4a
Revises: bc77de26374a
Create Date: 2020-07-10 09:05:58.489423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46719ce46e4a'
down_revision = 'bc77de26374a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tag', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='unique')
    # ### end Alembic commands ###
