"""empty message

Revision ID: effd5f580da2
Revises: e53a244af93c
Create Date: 2020-07-10 07:52:01.910152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'effd5f580da2'
down_revision = 'e53a244af93c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name_ko', sa.String(length=30), nullable=True),
    sa.Column('company_name_en', sa.String(length=30), nullable=True),
    sa.Column('company_name_ja', sa.String(length=30), nullable=True),
    sa.Column('company_tag_ko', sa.Text(), nullable=True),
    sa.Column('company_tag_en', sa.Text(), nullable=True),
    sa.Column('company_tag_ja', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('content', mysql.TEXT(collation='utf8_unicode_ci'), nullable=False),
    sa.Column('author_email', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=False),
    sa.Column('created_time', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('company')
    # ### end Alembic commands ###
