version: "3"
services:
  app:
    build: ./service
    container_name: flask_app
    restart: always
    volumes:
      - ./service/app:/app
    depends_on:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    expose:
      - 3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8080:80
